### ISSUE TITLE
[Doc] Regex used for substr function is optional, but documentation it is marked as mandatory

### ISSUE THREAD

**Issue by niveathika** [siddhi-io/siddhi-execution-string#33]
**Description:**
$subject. Also, Description of the substr() function is unclear

**Suggested Labels:**
Type/Documentation

**Suggested Assignees:**
@RukshiW @YvonneW

**Comment by mohanvive** [comment]
Fixed by Suho in https://github.com/siddhi-io/siddhi-execution-string/pull/52 ...
