### ISSUE TITLE
Improve logging in GetStringJSONFunctionExtension

### ISSUE THREAD

**Issue by pcnfernando** [siddhi-io/siddhi-execution-string#67]
**Description:**
Improve logging in GetStringJSONFunctionExtension

`INFO {io.siddhi.extension.execution.json.function.GetStringJSONFunctionExtension} - CollectorApp:query_2: Cannot find json element for the path 'field_462501'. Hence returning the default value 'null' (Encoded)`

**Comment by sahandilshan** [comment]
`SiddhiAppName:query1: Cannot find json element for the path '$.field'. Hence returning the default value 'null'.`  This is the log that print with the current implementation. What are the changes that should apply to this log message??
And I think this issue should belong to https://github.com/siddhi-io/siddhi-execution-json repository.

**Comment by mohanvive** [comment]
@pcnfernando Can you comment on above ?

**Comment by pcnfernando** [comment]
We can close this issue.
